name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Minimal ruxsatlar (Least Privilege)
permissions:
  contents: read

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        # Immutable Action SHA
        uses: actions/checkout@692973e3d9371296bf4051010375179853907409 
      
      - name: Setup Node.js
        # Immutable Action SHA
        uses: actions/setup-node@1e60f6205b5464e83c7908b896f1345d3e09156a
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Run Tests
        run: npm test

  security-scan:
    needs: build-and-test
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - uses: actions/checkout@692973e3d9371296bf4051010375179853907409
      - name: Initialize CodeQL
        uses: github/codeql-action/init@b6a47833a6932463e76a6e2e5050f55cf6a67f1b
        with:
          languages: javascript
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@b6a47833a6932463e76a6e2e5050f55cf6a67f1b
